AWSTemplateFormatVersion: "2010-09-09"
Description: 
  "Create ECR repository."

Parameters:
  EcrRepoName:
    Type: "String"
    Description: "Enter the name of the ECR Repository."
    Default: "ecr-repository"

Resources:
  LambdaEcrRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref "EcrRepoName"