AWSTemplateFormatVersion: "2010-09-09"
Description:
  "Create definitions for ECS services and tasks.
  You need to prepare a Service-Linked ecsServiceRole in advance."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - ClusterName
          - ServiceName
          - DesiredServiceCount
          - ImageURI
          - ContainerPort
          - HostPort
          - ContainerName

Parameters:
  ClusterName:
    Type: "String"
    Description: "Enter the name of the ECS Cluster."
    Default: "ecs-cluster"
  ServiceName:
    Type: "String"
    Description: "Enter the name of the ECS Service."
    Default: "ecs-service"
  DesiredServiceCount:
    Type: "Number"
    Description: "The desired number of containers for the service to run."
    Default: "1"
  ImageURI:
    Type: "String"
    Description: "Specify the image of the container to be launched."
    Default: "httpd:latest"
  ContainerPort:
    Type: "Number"
    Description: "Specifies the port number to connect to the container."
    Default: "80"
  HostPort:
    Type: "Number"
    Description: "Specifies the port number to connect to host."
    Default: "80"
  ContainerName:
    Type: "String"
    Description: "Specify the name of the container to run."
    Default: "Web-Server"

Resources:
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties: 
      ContainerDefinitions: 
        - Name: !Ref "ContainerName"
          Image: !Ref "ImageURI"
          Cpu: "0"
          Memory: "256"
          PortMappings: 
            - ContainerPort: !Ref "ContainerPort"
              HostPort: !Ref "HostPort"
          Essential: "true" 
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: !Sub "/ecs/${ServiceName}"
              awslogs-region: "ap-northeast-1"
              awslogs-stream-prefix: "ecs"
              awslogs-create-group: "true"
      Family: !Sub "${ServiceName}-task"
      NetworkMode: "bridge"
      Tags: 
        - Key: "Name"
          Value: !Sub "${ServiceName}-task"

  EcsService:
    Type: "AWS::ECS::Service"
    Properties: 
      ServiceName: !Ref "ServiceName"
      Cluster: !Ref "ClusterName"
      DesiredCount: !Ref "DesiredServiceCount"
      LaunchType: "EC2"
      SchedulingStrategy: "REPLICA"
      DeploymentConfiguration:
        MaximumPercent: "200"
        MinimumHealthyPercent: "50"
      Tags: 
        - Key: "Name"
          Value: !Ref "ServiceName"
      TaskDefinition: !Ref TaskDefinition